### ISSUE TITLE
Ignore messages sent by bot

### ISSUE THREAD

**Issue by jnhmcknight** [fictivekin/err-githubapi#2]
Currently when you open an issue via the bot, it will return the URL to the channel and then process the message with the URL outputting the issue information. This is redundant, because when the issue gets opened, the GitHub IRC hook sends the issue details to the channel, _and_ you have just created it, so you obviously know the title and who opened it.

![screenshot](https://www.dropbox.com/s/wa8legiw2rogdue/Screenshot%202016-09-15%2016.25.02.png?raw=1)

I realize the screenshot of the messages are not specifically in the right order, but this _is_ what is occurring.

**Comment by scoates** [comment]
It's surprising to me that errbot doesn't have an `IGNORE` array for users to ignore. If it did we could `IGNORE = ['github!*@*']`.

**Comment by jnhmcknight** [comment]
Added the specific ignore functionality to the plugin. Didn't want to :yakshave: the adding of it into `errbot` proper. Maybe one day, but today is not that day.

**Comment by jnhmcknight** [comment]
Closing. this was done a while back.
